config/routes.rb
Rails.application.routes.draw do

  get 'comments/index'

  get 'comments/new'

  root 'accounts#index'
  resources :accounts do
    resources :comments
  end
  devise_for :users, controllers:{registrations:'users/registrations'}
  get "accounts/invitation" => 'accounts#invitation', :as => :invitation
  resources :invitations
  get "checkuser", to:"invitations#checkuser"
  resources :teams do
    resources :comments
  end
  post "check", to:"teams#check"
  get "check_member", to: "teams#check_member"
  get "add_member", to:"teams#add_member"

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :comments, as: :commentable
  def self.all_accounts current_user_id
    @owner_account = Account.where(user_id: current_user_id).pluck(:id)#.to_a
    @find_invitation = Invitation.where(user_id: current_user_id).pluck(:account_id)
    @total_accounts = (@owner_account + @find_invitation)
    @account = Account.where(id: @total_accounts)
    return @account
    # @find_invitation.each do |invites|
    #   find_account = Account.find(invites.account_id)
    #   @account.push(find_account) 
    # end 
  end

    def owner_account(user)
      @owner_account = Account.where(user_id: user)
  end

    def owner_account_invitations(user)
      @owner_invitation = Invitation.where(user_id: user) 
    end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @account = Account.all_accounts(current_user.id)
  end

  def show
    @account = Account.find(params[:id])
    authorize Account
    @user_detail = Invitation.get_invite(params[:id])
    @team = Team.where(account_id: params[:id], owner_id: current_user.id)
    @team_member = TeamMember.team(current_user.id)
    @other_teams = TeamMember.other_team(current_user.id)
  end

private

  def account_params
  	 params.require(:account).permit!
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_team.html.erb
<div class="card" style="width: 18rem;">
  <div class="row" >
    <div class="card-body"><br>
    <div class="col"><h3><%=team.team_name%> team </h3></div>
    <p class="title"></p>
    <%= link_to 'Show Teams', team_path(team), class: "btn btn-primary"%>
  </div>
  </div>
  </div>



  

app/views/accounts/index.html.erb
<div class="container-narrow">    
  <div class="masthead">
    <div class="text-center"> 
      <div class="container">
        <u><h1>Accounts</h1></u>
        <div class="row">
          <%@account.each do |account|%>
            <div class="col-md-6">
              <div class="card" style="width: 30rem;" style="border-color:black;">
                <div class="row">
                  <div class="card text-primary border-primary">
                  <div class="card-body" class="card text-primary border-primary"><br>
                    <h4 class="card-title"><%= account.account_name%></h4>
                      <%= link_to 'View Account', account_path(account.id), class: "btn btn-danger"%>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            </div> 
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="container-narrow">    
  <div class="masthead">    
    <div class="text-right">
          <button type="button" class="btn btn-danger" class="col-md-6 text-right" data-toggle="modal" data-target="#myModal">Invite new users </button>
      <button type="button" class="btn btn-primary" class="button" data-toggle="modal" data-target="#Teams">Add Teams </button></div>
  </div>
</div>

<div class="text-center"><h3><u>Account Members</u></h3></div>
<div class="container">
  <div class="table-bordered table-responsive text-center">
    <table class="table table-bordered">
    <thead  class="thead-dark">
      <tr>
        <th style="border-color:black;" scope="col"><h4>Name</h4></th>
        <th style="border-color:black;" scope="col"><h4>Email</h4></th>
      </tr>
    </thead>
    <tbody>
      <%@user_detail.each do |a|%>
        <tr  class="table-active">
          <td style="border-color:black;"> <%= a.name%> </td>
          <td style="border-color:black;"> <%= a.email%></td>
        </tr>
      <%end%>
    </tbody>
  </table>

<!-- My Teams -->
  <% if @team.present? %>
    <h3><u>My Teams</u></h3>
        <div class="row">
          <% @team.each do |team|%>
            <div class="col-md-4">
              <%= render 'team', team: team %>
            </div>
          <%end%>
        </div>
  <%end%>


<!-- Other Teams -->
  <% if @other_teams.present? %>
  <h3><u>Other Teams</u></h3>
    <div class="row">
      <% @other_teams.each do |team|%>
        <div class="col-md-4">
          <%= render 'team', team: team %>
        </div>
      <%end%>
    </div>
  <%end%>

  <%= render partial: "comments/comments", locals:{commentable: @account} %>
  <%= render partial: "comments/form", locals:{commentable: @account} %>


<!-- Modal for invitations -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        
    <!-- Modal content-->
      <div class="modal-content">
         <div class="">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title"></h4>
          </div>
          <div class="modal-body">
            <%= form_with scope: :invitation, url: invitations_path(account_id: @account.id), local: true do |form| %>
              <p>
                <%= form.label :Email %><br>
                <%= form.email_field :email %>
              </p>

              <p>
              <%= form.submit %>
              </p>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"> close</button>
          </div>
      </div>
    </div>
  </div>

<!-- Modal for Teams -->
<div class="modal fade" id="Teams" role="dialog">
  <div class="modal-dialog">
          
<!-- Modal content-->

    <div class="modal-content">
      <div class="">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
        <%= form_with scope: :team, url: teams_path(@team), local: true do |form| %>
          <p>
            <%= form.label :Team_name %><br>
            <%= form.text_field :team_name %>
            <%= form.hidden_field :owner_id , :value => @current_user.id %>
              <%= form.hidden_field :account_id , :value => params[:id] %>
          </p>
          <p>
            <%= form.submit %>
          </p>

        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"> close</button>
      </div>
    </div>
  </div>
</div>
    